/:
  controller: Base
  action: index


/login:
  controller: Auth
  action: login


/register:
  controller: Auth
  action: register


/password_reset:
  controller: Auth
  action: password_reset


/verify:
  controller: Auth
  action: verify


/reset_password:
  controller: Auth
  action: reset_password


/logout:
  controller: Auth
  action: logout


/home:
  controller: Base
  action: home


/pages:
  controller: Page
  action: list


/page_view:
  controller: Page
  action: view


/page_create:
  controller: Page
  action: create


/page_edit:
  controller: Page
  action: edit


/admin:
  controller: Admin
  action: index


/manage_users:
  controller: Admin
  action: manage_users


/manage_pages:
  controller: Admin
  action: manage_pages