/:
  controller: Base
  action: index


/login:
  controller: Auth
  action: login


/register:
  controller: Auth
  action: register


/password_reset:
  controller: Auth
  action: password_reset


/home:
  controller: Base
  action: home


/admin:
  controller: Admin
  action: index


/manage_users:
  controller: Admin
  action: manage_users